SELECT GISID 
      ,sum(CASE WHEN ED_PRO = "Even" THEN 1 ELSE 0 END) AS "EDPRO_EVEN"
	  ,sum(CASE WHEN ED_PRO = "Higher" THEN 1 ELSE 0 END) AS "EDPRO_HIGHER"
	  ,sum(CASE WHEN ED_PRO = "Lower" THEN 1 ELSE 0 END) AS "EDPRO_LOWER"
	  ,sum(CASE WHEN DRAIN = "Good" THEN 1 ELSE 0 END) AS "DRAIN_GOOD"
	  ,sum(CASE WHEN DRAIN = "Fair" THEN 1 ELSE 0 END) AS "DRAIN_FAIR"
	  ,sum(CASE WHEN DRAIN = "Poor" THEN 1 ELSE 0 END) AS "DRAIN_POOR" 
FROM ArlingtonHeights_Testing
GROUP BY GISID